version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rB4dRlyn38F75Sg13Xd5iNM1wfSYZY708gh
      MYSQL_DATABASE: dev
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: rB4dRlyn38F75Sg13Xd5iNM1wfSYZY708gh
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
